### ISSUE TITLE
Circle of fifts Addition

### ISSUE THREAD

**Issue by GoranKovac** [xupeng1206/ReaChord#1]
Hi it would be cool to also have this addition (as the native software has it). I've prepared the code for you.
Hope you will find it useful and implement. Cheers!
[PieFifts.txt](https://github.com/xupeng1206/ReaChord/files/13400775/PieFifts.txt)

**Comment by xupeng1206** [comment]
Thanks code, I will merge into main branch later.

**Comment by xupeng1206** [comment]
Merged https://github.com/xupeng1206/ReaChord/pull/4
