### ISSUE TITLE
用reapack下载脚本之后，动作列表里不会自动添加脚本。

### ISSUE THREAD

**Issue by wenxm611** [xupeng1206/ReaChord#2]
![reaper_D2EpewMhYz](https://github.com/xupeng1206/ReaChord/assets/131326271/fe49c57b-ba48-4eb8-ac2b-37f4a282b936)

**Comment by xupeng1206** [comment]
你再试一下，我昨天刚刚更新，应该可以了

**Comment by wenxm611** [comment]
> 你再试一下，我昨天刚刚更新，应该可以了

可以啦~
